server:
  port: 8081

output:
  ansi:
    enabled: always

astra:
  secure-connect-bundle: secure-connect-bundle.zip
  username: <client-id>
  password: <client-secret>
  keyspace: <keyspace>
  schema-action: create-if-not-exists
  request:
      timeout: 10s
  connection:
    connect-timeout: 10s
    init-query-timeout: 10s    
