server:
  port: 8081

spring:
  application:
    name: decks-service

output:
  ansi:
    enabled: always

astra:
  secure-connect-bundle: secure-connect-bundle.zip
  username: <client-id>
  password: <client-secret>
  keyspace: <keyspace>    
